Implemented guardrail service with APIs to effectively manage guardrails in the system #160
privacera/paig pull request #165
Opened 2024-12-20 12:41 UTC by vinayakbagal7

## Change Description

Implemented guardrail service with APIs to effectively manage guardrails in the system
1. Added APIs to handle all CRUD operations for guardrail connections.
> Example payload -
> ```
>{
>    "name": "gr_connection_1",
>    "description": "test description",
>    "guardrailsProvider": "AWS",
>    "connectionDetails": {
>        "access_key": "<aws_access_key>",
>        "secret_key": "<aws_secret_ky>",
>        "session_token": "<aws_session_token>"
>    },
>    "encryptFields": ["secret_key", "session_token"]
>}
>```
2. API to test connections to external services with the same payload as above.
3. APIs to handle all CRUD operations for guardrails.
4. Handled different types of configurations below in the guardrail.
> 1. Content Moderation
> 2. Off Topics filters
> 3. Denied Terms
> 4. Sensitive Data Filtering
> 5. Prompt Safety

Example payload for guardrail -
> ```
>{
>    "name": "test_gr_1",
>    "description": "test guardrail 1",
>    "version": 1,
>    "applicationKeys": [
>        "632bc4a449580d9766f5845179bb8b6e",
>        "6b2d2f21acdac859d3fb3804484b99a7",
>        "5c4c5df2daca1210f34120af6c689187"
>    ],
>    "guardrailConnectionName": "gr_connection_1",
>    "guardrailProvider": "AWS",
>    "guardrailConfigs": [
>        {
>            "configType": "CONTENT_MODERATION",
>            "responseMessage": "I couldn't respond to that message.",
>            "configData": {
>                "configs": [
>                    {
>                        "category": "Hate",
>                        "filterStrengthPrompt": "high",
>                        "filterStrengthResponse": "medium"
>                    },
>                    {
>                        "category": "Insults",
>                        "filterStrengthPrompt": "high",
>                        "filterStrengthResponse": "medium"
>                    }
>                ]
>            }
>        },
>        {
>            "configType": "SENSITIVE_DATA",
>            "responseMessage": "I couldn't respond to that message.",
>            "configData": {
>                "configs": [
>                    {
>                        "category": "EMAIL",
>                        "action": "DENY"
>                    },
>                    {
>                        "category": "USERNAME",
>                        "action": "ALLOW"
>                    },
>                    {
>                        "category": "PASSWORD",
>                        "action": "REDACT"
>                    },
>                    {
>                        "type": "regex",
>                        "name": "email_regex",
>                        "description": "email_regex",
>                        "pattern": "test_pattern",
>                        "action": "REDACT"
>                    }
>                ]
>            }
>        },
>        {
>            "configType": "OFF_TOPIC",
>            "responseMessage": "I couldn't respond to that message.",
>            "configData": {
>                "configs": [
>                    {
>                        "topic": "Sports",
>                        "definition": "Sports Definition",
>                        "samplePhrases": [
>                            "Who's playing NFL tonight ?",
>                            "Who's leading tonight ?"
>                        ],
>                        "action": "DENY"
>                    }
>                ]
>            }
>        },
>        {
>            "configType": "DENIED_TERMS",
>            "responseMessage": "I couldn't respond to that message.",
>            "configData": {
>                "configs": [
>                    {
>                        "type": "PROFANITY",
>                        "value": true
>                    },
>                    {
>                        "term": "Violance",
>                        "keywords": [
>                            "Violent Bahaviour",
>                            "Physical Assault"
>                        ]
>                    }
>                ]
>            }
>        },
>        {
>            "configType": "PROMPT_SAFETY",
>            "responseMessage": "I couldn't respond to that message.",
>            "configData": {
>                "configs": [
>                    {
>                        "category": "PROMPT_ATTACK",
>                        "filterStrengthPrompt": "HIGH"
>                    }
>                ]
>            }
>        }
>    ]
>}
>```
5. CRUD API to manage response message templates.

6. "Get Guardrail" API specifically for the shield service based on lastKnownVersion.
Example response -
>```
>{
>    "applicationKey": "632bc4a449580d9766f5845179bb8b6e",
>    "version": 3,
>    "guardrails": [
>        {
>            "id": 1,
>            "status": 1,
>            "createTime": "2024-12-20T08:46:36.899617",
>            "updateTime": "2024-12-20T08:52:36.900342",
>            "name": "test_gr_1",
>            "description": "test guardrail 1",
>            "version": 6,
>            "guardrailProvider": "AWS",
>            "guardrailConnectionName": "gr_connection_1",
>            "guardrailConfigs": [
>                {
>                    ...
>                }
>            ],
>            "guardrailProviderResponse": {
>                "success": true,
>                "response": {
>                    "guardrailId": "j0vwca4b8swg",
>                    "guardrailArn": "arn:aws:bedrock:us-east-1:404161567776:guardrail/j0vwca4b8swg",
>                    "version": "DRAFT"
>                }
>            },
>            "guardrailConnectionDetails": {
>                "access_key": "<aws_secret_key>",
>                "secret_key": "<aws_secret_key_encrypted>",
>                "session_token": "<aws_session_token_encrypted>"
>            }
>        }
>    ]
>}
>```

## Issue reference

This PR fixes issue [#160](https://github.com/privacera/paig/issues/160)

## Checklist

- [x] I have reviewed the [contribution guidelines](https://github.com/privacera/paig/blob/main/docs/CONTRIBUTING.md)
- [x] My code includes unit tests
- [x] All unit tests and lint checks pass locally
- [x] My PR contains documentation updates/additions if required

2025-01-10 09:57 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/api_schemas/guardrail.py
> +    A model representing the Guardrails data.
Is this used to return response to shield ? If yes can we put in comments

2025-01-10 09:58 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/controllers/gr_connection_controller.py
> +        # TODO: background_capture_event(event=UpdateAIApplicationEvent())
Remove this

2025-01-10 09:58 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/controllers/gr_connection_controller.py
> +        # TODO: background_capture_event(event=DeleteAIApplicationEvent())
Remove this

2025-01-10 09:59 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/controllers/guardrail_controller.py
> +        # await background_capture_event(event=CreateAIApplicationEvent())
Remove this

2025-01-10 09:59 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/controllers/guardrail_controller.py
> +        # await background_capture_event(event=UpdateAIApplicationEvent())
Remove unnecessary line

2025-01-10 09:59 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/controllers/guardrail_controller.py
> +        # await background_capture_event(event=DeleteAIApplicationEvent())
Remove unnecessary line

2025-01-10 10:03 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/database/db_models/guardrail_model.py
> +    guardrail_provider = Column(SQLEnum(GuardrailProvider), nullable=False)
do we need guardrail provider in this table ?

2025-01-10 10:35 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/database/db_operations/response_template_repository.py
> +            db_session (Session): The database session to use for operations.
there is no db_session arg in parameter

2025-01-13 05:57 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        Check if a Guardrail already exists by its name.
The method name and this description is not matching, the method name should be changed

2025-01-13 06:03 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        if request.guardrail_provider is not None and request.guardrail_connection_name is None:
We can do it like this
```
if not request.guardrail_provider:
    raise BadRequestException(get_error_message(ERROR_FIELD_REQUIRED, "Guardrail Provider"))
if not request.guardrail_connection_name or request.guardrail_connection_name == "":
    raise BadRequestException(get_error_message(ERROR_FIELD_REQUIRED, "Guardrail Connection Name"))
```

2025-01-13 06:05 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        if request.guardrail_connection_name is not None and request.guardrail_provider is not None:
isn't this validation already there in validator ?

2025-01-13 06:06 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +                raise BadRequestException(f"Guardrail Connection with name {[request.guardrail_connection_name]} not found for provider {[request.guardrail_provider.name]}")
isn't this validation already there in validator ?

2025-01-13 06:13 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        guardrails = await self.gr_view_repository.get_all(filters={"guardrail_id": id})
Lets add comment here that we are using view where there are multiple entries for the same guardrail with multiple config types, this combined view enhance api speed and reduce database calls and that's why we are not directly using `get_record_by_id` method

2025-01-13 09:51 UTC, vinayakbagal7 commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        if request.guardrail_provider is not None and request.guardrail_connection_name is None:
this guardrail_provider and connection both will be none if user wants to use only sensitive data with default paig guardrail but if value is provided for any of one the other one becomes necessary that's why this condition is added rather than simple one mentioned by you

2025-01-13 09:52 UTC, vinayakbagal7 commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        if request.guardrail_connection_name is not None and request.guardrail_provider is not None:
yes, but if both are none then we don't create guardrails to end service that's why added this check

2025-01-13 09:59 UTC, vinayakbagal7 commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +                raise BadRequestException(f"Guardrail Connection with name {[request.guardrail_connection_name]} not found for provider {[request.guardrail_provider.name]}")
this is not covered in validator

2025-01-14 05:04 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        return config["guardrail"]["application_version"]
what is this version ?

2025-01-14 05:08 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        if request.guardrail_provider is not None and request.guardrail_connection_name is None:
can we add comment in the code for this

2025-01-14 05:09 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        if request.guardrail_connection_name is not None and request.guardrail_provider is not None:
okay, lets add comment in the code above if statement

2025-01-14 06:26 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        await self._bump_up_version_in_gr_apps(gr_app_keys)
We are going to delete the entries, so do we need to bump up version here ?

2025-01-14 07:02 UTC, akshayr-privacera-github requested changes
Lets do the required changes

2025-01-16 05:47 UTC, vinayakbagal7 commented on paig-server/backend/paig/api/guardrails/database/db_models/guardrail_model.py
> +    guardrail_provider = Column(SQLEnum(GuardrailProvider), nullable=False)
Yes it's used in the service class business logic

2025-01-16 06:13 UTC, vinayakbagal7 commented on paig-server/backend/paig/api/guardrails/services/guardrails_service.py
> +        await self._bump_up_version_in_gr_apps(gr_app_keys)
Incrementing the version in case of delete guardrail as well. This is because one application can have multiple guardrail associated with it and if we delete this version it will impact the get_by_app_key API

2025-01-16 06:15 UTC, akshayr-privacera-github submitted a review, later dismissed

2025-02-07 07:36 UTC, akshayr-privacera-github commented on paig-server/backend/paig/api/guardrails/providers/backend/bedrock.py
> +
I think we have missed one of the conditions which is needed for kubernetes service account deployment
```
if os.getenv("AWS_ROLE_ARN") and os.getenv("AWS_WEB_IDENTITY_TOKEN_FILE"):
    sts_client = boto3.client('sts')
    assumed_role = sts_client.assume_role_with_web_identity(
        RoleArn=os.getenv("AWS_ROLE_ARN"),
        RoleSessionName="bedrock-guardrail-session",
        WebIdentityToken=open(os.getenv("AWS_WEB_IDENTITY_TOKEN_FILE")).read().strip()
    )
    temp_credentials = assumed_role['Credentials']
    return boto3.client(
        'bedrock',
        aws_access_key_id=temp_credentials['AccessKeyId'],
        aws_secret_access_key=temp_credentials['SecretAccessKey'],
        aws_session_token=temp_credentials['SessionToken'],
        region_name=self.connection_details['region']
    )
```

2025-02-07 07:47 UTC, akshayr-privacera-github requested changes
Handle assume role in k8s based deployment with service account assigned to pod

2025-02-10 06:41 UTC, amrakshay approved these changes
Approved

2025-02-10 06:42 UTC, akshayr-privacera-github approved these changes
Approved

2025-02-19 06:27 UTC, pravin-bansod commented on paig-server/backend/paig/conf/default_config.yaml
> +    cache_cleanup_interval_sec: 60
is this needed

2025-02-19 06:42 UTC, vinayakbagal7 commented on paig-server/backend/paig/conf/default_config.yaml
> +    cache_cleanup_interval_sec: 60
Removed this as not needed now

2025-02-26 07:46 UTC, SiddheshwarKamble approved these changes

2025-02-28 07:03 UTC, SiddheshwarKamble approved these changes

2025-02-28 07:37 UTC, pravin-bansod commented on paig-server/backend/paig/routers.py
> +router.include_router(paig_guardrails_router, prefix="/guardrail-service/api", dependencies=[Depends(get_auth_user)])
check this

2025-02-28 08:28 UTC, pravin-bansod approved these changes

2025-02-28 08:28 UTC, amrakshay approved these changes

2025-02-28 08:29 UTC, SiddheshwarKamble approved these changes

2025-02-28 08:31 UTC, adityasinght approved these changes

2025-02-28 08:34 UTC, merged